INSERT INTO carrera VALUES('1','ING CIVIL COMPUTACION');
INSERT INTO carrera VALUES('2','ING CIVIL INDUSTRIAL');
INSERT INTO carrera VALUES('3','ING CIVIL OBRAS CIVILES');
INSERT INTO carrera VALUES('4','ING CIVIL MECANICA');
INSERT INTO carrera VALUES('5','ING CIVIL MECATRONICA');
INSERT INTO carrera VALUES('6','ING CIVIL ELECTRICA');
INSERT INTO carrera VALUES('7','ING CIVIL MINAS');
INSERT INTO carrera VALUES('8','ING INFORMATICA EMPRESARIAL');
INSERT INTO carrera VALUES('9','PSICOLOGIA');
INSERT INTO carrera VALUES('10','MUSICA');
INSERT INTO carrera VALUES('11','MEDICINA');
INSERT INTO carrera VALUES('12','ING COMERCIAL');
INSERT INTO carrera VALUES('13','DERECHO');
INSERT INTO carrera VALUES('14','ING FORESTAL');
INSERT INTO carrera VALUES('15','DISENO');
INSERT INTO carrera VALUES('16','ENFERMERIA');
INSERT INTO carrera VALUES('17','ODONTOLOGIA');
INSERT INTO carrera VALUES('18','ARQUITECTURA');
INSERT INTO carrera VALUES('19','AGRONOMIA');
INSERT INTO carrera VALUES('20','KINESIOLOGIA');
INSERT INTO ramo VALUES('1','Calculo');
INSERT INTO ramo VALUES('2','Fisica');
INSERT INTO ramo VALUES('3','Quimica');
INSERT INTO ramo VALUES('4','Comunicacion Oral y Escrita');
INSERT INTO ramo VALUES('5','Introducion a la Programacion');
INSERT INTO ramo VALUES('6','Programacion');
INSERT INTO ramo VALUES('7','Solucion Algoritmica de Problemas');
INSERT INTO ramo VALUES('8','Programacion Avanzada');
INSERT INTO ramo VALUES('9','Proyecto de Programacion');
INSERT INTO ramo VALUES('10','Diseno de Bases de Datos');
INSERT INTO ramo VALUES('11','Recursos Humanos');
INSERT INTO ramo VALUES('12','Modelos Discretos');
INSERT INTO ramo VALUES('13','Ingles');
INSERT INTO ramo VALUES('14','Intruccion a la Teoria de Sistemas');
INSERT INTO ramo VALUES('15','Ecuaciones Diferenciales');
INSERT INTO ramo VALUES('16','Algebra Lineal');
INSERT INTO ramo VALUES('17','Requisitos de Software');
INSERT INTO ramo VALUES('18','Interfaz Humano Computador');
INSERT INTO ramo VALUES('19','Algoritmos y Estructuras de Datos');
INSERT INTO ramo VALUES('20','Trabajo en Equipo y Liderazgo');
